import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

import "./globals.css";

import Footer from "@/components/Footer";
import RootProviders from "@/providers/RootProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Budget Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className="scroll-smooth antialiased"
        suppressHydrationWarning
      >
        <body
          className={`flex min-h-screen flex-col ${inter.className} ${"theme-orange"}`}
        >
          <RootProviders>
            <main className="grow">
              <Toaster richColors />
              {children}
            </main>
            <Footer />
          </RootProviders>
        </body>
      </html>
    </ClerkProvider>
  );
}
